//using Xunit;
//using FileCombiner;
//using System.IO;

//namespace FileCombinerTests
//{
//    public class FileCombinerTests
//    {
//        [Fact]
//        public void IsNotAutoGenerated_AutoGeneratedFile_ReturnsFalse()
//        {
//            // Arrange
//            var fileCombiner = new Form1();
//            var autoGeneratedFile = "C:\\data3\\ssc\\sss7\\SampleAutoGeneratedFile.cs";
//            File.WriteAllText(autoGeneratedFile, "// This code was auto-generated by a tool.\r\n// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.");

//            // Act
//            bool result = fileCombiner.IsNotAutoGenerated(autoGeneratedFile);

//            // Assert
//            Assert.False(result);
//        }

//        [Fact]
//        public void IsNotAutoGenerated_NotAutoGeneratedFile_ReturnsTrue()
//        {
//            // Arrange
//            var fileCombiner = new Form1();
//            var notAutoGeneratedFile = "C:\\data3\\ssc\\sss7\\SampleNotAutoGeneratedFile.cs";
//            File.WriteAllText(notAutoGeneratedFile, "using System;\r\n\r\nnamespace SampleNamespace\r\n{\r\n    public class SampleClass\r\n    {\r\n        public void SampleMethod()\r\n        {\r\n            Console.WriteLine(\"Hello, World!\");\r\n        }\r\n    }\r\n}");

//            // Act
//            bool result = fileCombiner.IsNotAutoGenerated(notAutoGeneratedFile);

//            // Assert
//            Assert.True(result);
//        }
//    }
//}

